{
 "title": "mmurygin/infra-metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "city", "query": "label_values(city)" }
  ]
 },
 "panels": [
  {
   "title": "RPS by status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{app=\"provider_backend\", namespace=\"saratov\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Request percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{app=\"provider_backend\", namespace=\"$city\"}[5m])) by (le))",
     "legendFormat": "99p"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{app=\"provider_backend\", namespace=\"$city\"}[5m])) by (le))",
     "legendFormat": "95p"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{app=\"provider_backend\", namespace=\"$city\"}[5m])) by (le))",
     "legendFormat": "90p"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{app=\"provider_backend\", namespace=\"$city\"}[5m])) by (le))",
     "legendFormat": "75p"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{app=\"provider_backend\", namespace=\"$city\"}[5m])) by (le))",
     "legendFormat": "50p"
    }
   ]
  },
  {
   "title": "% Pods Running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$city\"}) / count(up{job=\"$city\"})",
     "legendFormat": "% pods running"
    }
   ]
  },
  {
   "title": "CPU Usage (app)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", namespace=\"$city\", pod!~\"$city-mysql-.*\"}[5m]))  by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage (app)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",container!=\"\", pod=~\"$city-.*\", pod!~\"$city-mysql-.*\", namespace=\"$city\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage (mysql)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", namespace=\"$city\", pod=~\"$city-mysql-.*\", namespace=\"$city\"}[5m]))  by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage (mysql)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",container!=\"\", pod=~\"$city-mysql-.*\", namespace=\"$city\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}